---
author: "John Steill"
title: "Marioni data transformed to SingleCellExperiment Format"
date: "`r Sys.Date()`"
---

``` {r 1_Prelims, message=FALSE}
library(SingleCellExperiment)
library(Matrix)
library(CHETAH)
```

# Where Python Left Off:
* We downloaded the Marioni Data and uncompressed it.
* Downsampled 2(00) cells of each type. 

``` {r 2_Load_Reduced_Data}
input_counts = as.matrix(read.csv(
    '../Data/Processed/sub_0794_downsampled.csv',
    header=TRUE,
    row.names="Genes"))
ref_counts = as.matrix(read.csv(
    '../Data/Processed/raw_downsampled_counts.csv',
    header=TRUE,
    row.names="Genes"))
ref_ct = read.csv('../Data/Processed/downsampled_celltypes.csv',
    header=T,
    row.names="sample_num")
row.names(ref_ct) <- make.names(row.names(ref_ct))
reference <- SingleCellExperiment(
    assays = list(counts = ref_counts),
    colData = DataFrame(celltypes = as.character(ref_ct[,1])))
input <- SingleCellExperiment(assays = list(counts = input_counts))
output <- CHETAHclassifier(input = input, ref_cells = reference)
```

